[launcher]
author=James Campbell
description=Beelzebub Honeypot - Dashboards, Reports, and Alerts
version=1.0.0
build=2

[package]
id=SA-beelzebub
check_for_updates=0

[ui]
is_visible=1
label=Beelzebub
