[beelzebub_first_seen_src_ip]
field.first_seen = number
field.last_seen  = number
field.events     = number
field.protocols  = string
accelerated_fields.accel_first_seen = {"first_seen": 1}

[beelzebub_first_seen_credential]
field.first_seen    = number
field.last_seen     = number
field.events        = number
field.username      = string
field.password      = string
field.sample_src_ip = string
accelerated_fields.accel_first_seen = {"first_seen": 1}

[beelzebub_first_seen_command]
field.first_seen    = number
field.last_seen     = number
field.events        = number
field.command       = string
field.sample_src_ip = string
accelerated_fields.accel_first_seen = {"first_seen": 1}

[beelzebub_first_seen_uri]
field.first_seen    = number
field.last_seen     = number
field.events        = number
field.http_method   = string
field.uri_path      = string
field.sample_src_ip = string
accelerated_fields.accel_first_seen = {"first_seen": 1}

[beelzebub_first_seen_user_agent]
field.first_seen      = number
field.last_seen       = number
field.events          = number
field.http_user_agent = string
field.sample_src_ip   = string
accelerated_fields.accel_first_seen = {"first_seen": 1}

[beelzebub_first_seen_client]
field.first_seen    = number
field.last_seen     = number
field.events        = number
field.client        = string
field.sample_src_ip = string
accelerated_fields.accel_first_seen = {"first_seen": 1}
