[beelzebub_first_seen_src_ip]
external_type = kvstore
collection    = beelzebub_first_seen_src_ip
fields_list   = _key, src_ip, first_seen, last_seen, events, protocols

[beelzebub_first_seen_credential]
external_type = kvstore
collection    = beelzebub_first_seen_credential
fields_list   = _key, username, password, first_seen, last_seen, events, sample_src_ip

[beelzebub_first_seen_command]
external_type = kvstore
collection    = beelzebub_first_seen_command
fields_list   = _key, command, first_seen, last_seen, events, sample_src_ip

[beelzebub_first_seen_uri]
external_type = kvstore
collection    = beelzebub_first_seen_uri
fields_list   = _key, http_method, uri_path, first_seen, last_seen, events, sample_src_ip

[beelzebub_first_seen_user_agent]
external_type = kvstore
collection    = beelzebub_first_seen_user_agent
fields_list   = _key, http_user_agent, first_seen, last_seen, events, sample_src_ip

[beelzebub_first_seen_client]
external_type = kvstore
collection    = beelzebub_first_seen_client
fields_list   = _key, client, first_seen, last_seen, events, sample_src_ip
